export const footerInfo = {
  "Audit Service": [
    "Ethereum Audit",
    "Polygon Audit",
    "BSC Audit",
    "Solana Audit",
    "NEAR Audit",
    "Algorand Audit",
    "Tezos Audit",
    "Hyperledger Fabric Audit",
    "L1 Audit",
    "Polkadot Audit",
    "Wallet Audit",
    "ZkSync Audit",
    "Starknet Audit",
  ],
  "Quill Ecosystem": [
    "QuillAI",
    "QuillCheck",
    "QuillShield",
    "QuillAcademy",
    "      QuillMonitor",
    "Web3Suggest",
    "      Explore All Tools",
  ],
  "Other Services": [
    "Red Teaming",
    "dApp Pentesting",
    "DeFi Diligence",
    "NFT Due Diligence",
    "Rug Pull Due Diligence",
    "Security Consultation",
    "Blockchain Forensics",
    "KYC (Know Your Customer)",
  ],
  "Quick Links": [
    "Pricing",
    "Audit Process",
    "Our Audits",
    "Testimonials",
    "Security Synopsis",
    "Blog",
    "Clients",
    "Careers Hiring",
  ],
};
